spring:
  jpa.hibernate.ddl-auto: false
---
spring:
  profiles: production
spring.datasource:
  platform: mysql
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/test-spring-web
  username: root
  password:
---
spring:
  profiles: test
  jpa.show-sql: true
spring.datasource:
  platform: h2
  driverClassName: org.h2.Driver
  url: jdbc:h2:mem:test-spring-web;MODE=MySQL
